### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by zen010101** [musug/obsidian-paste-png-to-jpeg#1]
I installed and config it and pasting a image into the Obsidian, the plugin is not working that the .PNG is not converted into the .JPG

**Comment by toxfu** [comment]
yes, not working at all

**Comment by musug** [comment]
@zen010101 
@toxfu 
I understand, the original purpose of this plug-in is used to change the screenshot image to jpeg, you should be by directly pasting the png to the notes needs, I modify, version 1.01 has achieved this function

**Comment by zen010101** [comment]
> @zen010101 @toxfu I understand, the original purpose of this plug-in is used to change the screenshot image to jpeg, you should be by directly pasting the png to the notes needs, I modify, version 1.01 has achieved this function

换句话说1.01才实现 png2jpg 是吧？
另外，粘贴改名，和自动将图片放到笔记下面 这两个功能 建议留个开关给用户，未必都需要。

**Comment by zen010101** [comment]
我安装了1.01，结果还是没有任何效果。粘贴的图片仍然是 PNG

**Comment by musug** [comment]
@zen010101 
确实可以添加个开关

1.0.0实现的是截图的转换. 比如win10中的 win+shift + s
1.0.1把直接复制图片到笔记中也进行了处理.

如果都不产生作用, 我怀疑是不是和其他插件冲突了.
你可以试试把其他插件都关闭了

**Comment by PandaraWen** [comment]
+1 同样不起作用。
<img width="629" alt="image" src="https://user-images.githubusercontent.com/3304493/167276496-81397a46-d208-4410-a80d-c983436566c8.png">
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/3304493/167276500-caa0a9bf-32c4-4b5d-865b-da260584e39c.png">

**Comment by musug** [comment]
@zen010101 
@PandaraWen 
@toxfu 

我这边正常
麻烦把所有的插件列表 以及 obsidian的版本给出来, 我直接来重现下. 
现在完全想不到是哪个点出问题了 ~~

**Comment by PandaraWen** [comment]
@musug 在这里～
<img width="449" alt="image" src="https://user-images.githubusercontent.com/3304493/167289847-991e1b4e-e44d-4835-8a45-9d43341f02dd.png">
![image](https://user-images.githubusercontent.com/3304493/167289878-b3192cd4-3a20-4a26-9ea2-4a6d365a300e.png)

**Comment by zen010101** [comment]
![image](https://user-images.githubusercontent.com/60574100/167299590-a963b485-c3c8-4a8c-aebe-e221bf370287.png)

**Comment by zen010101** [comment]
> @zen010101 @PandaraWen @toxfu
> 
> 我这边正常 麻烦把所有的插件列表 以及 obsidian的版本给出来, 我直接来重现下. 现在完全想不到是哪个点出问题了 ~~

使用 0.14.6 版本 Ob，然后 新建 一个库，然后安装你这个插件，然后使用微信桌面版本 Alt-A 进行截屏，然后 粘贴 到 Ob，啥都没有发生，还是 PNG 图片。

**Comment by kevinawoo** [comment]
I had to create 2 folders for it to work
- `$yourvault/image`
- `$yourvault/attachments/image`

**Comment by musug** [comment]
@zen010101 
@PandaraWen
@toxfu
@basekno 

我也用上面的各种环境搭测试了, 但是都是正常的. 
突然想起我的是windows 10, 会不是回各位的是macos...
手上没mac, 这几天折腾了下虚拟机装,macos, 嗯很不幸, obsidian打开黑屏
所以 如果是macos的话, 我暂时没办法处理这个兼容性的bug了.

**Comment by musug** [comment]
@kevinawoo 
This function will be modified, I designed this function, did not find obsidian has the function to set the default image path, in order not to interfere with the .md file, so the design of the function to move the image to the directory.
