### ISSUE TITLE
Support for multiple images per note

### ISSUE THREAD

**Issue by kevinawoo** [musug/obsidian-paste-png-to-jpeg#2]
On version 1.0.1, if I try to paste in another image that already had a compressed image, it throws a file already exists error.

Proposed solution: add some kind of unique identifier at the end of the filename.
ex: `{markdownFileName} ${datetimestamp}.jpeg`

**Comment by musug** [comment]
You are right, this will not only solve possible conflict problems, but also improve efficiency. This feature will be improved in the next version

**Comment by kevinawoo** [comment]
If you use seconds or ms in the timestamp it's very unlikely you'll get collisions. 

I think it's fine if users accidentally double paste, to let them handle cleaning up the dup.
