### ISSUE TITLE
Turn off Auto Rename but plugin still auto-renames all pasted images 

### ISSUE THREAD

**Issue by nhan000** [musug/obsidian-paste-png-to-jpeg#3]
as in the title. The plugin renamed all pasted images even though I have turned the Auto rename feature off.

**Comment by musug** [comment]
@nhan000 
Sorry, recently too busy, really do not have time, I need to wait for the completion of the project in hand, in order to fix the bug

**Comment by bboerzel** [comment]
#6 
Hi I tried to fix the issue.
@musug please try to compile, I only made the changes directly in the main.js of the installed plugin.
Best regards

**Comment by musug** [comment]
> #6 嗨，我试图解决这个问题。 @musug请尝试编译，我只直接在已安装插件的主.js中进行了更改。 此致敬意



> #6 Hi I tried to fix the issue. @musug please try to compile, I only made the changes directly in the main.js of the installed plugin. Best regards
Thank you for your modification. A new version has been released to fix the bug
