### ISSUE TITLE
Unnavailable under "community plugins"

### ISSUE THREAD

**Issue by steve-hadley** [musug/obsidian-paste-png-to-jpeg#7]
Hi there, I can't find this in the community plugins listed in Obsidian. Is that intentional?

**Comment by Scutum-L** [comment]
I just installed it from the community plugins list. It's called "Paste image Png to Jpeg".

**Comment by steve-hadley** [comment]
Very strange I couldn't find it when I looked but if it's displaying now I'll close this, thanks @Scutum-L!
